// Code generated by datly link sync. Additive only.
package catalogpredicate

import "reflect"

var _datlyReachableReportCatalogRead = reflect.TypeFor[ReportCatalogRead]()
var _datlyReachableRunNamespaceRead = reflect.TypeFor[RunNamespaceRead]()

func init() {}
