import React, { useEffect, useMemo, useState } from 'react';
import { Button, ButtonGroup, Callout, Card, Dialog, DialogBody, DialogFooter, FormGroup, HTMLSelect, HTMLTable, InputGroup, NumericInput, Tag } from '@blueprintjs/core';
import { filterPredicateGroups, filterPredicateRows, predicateGroups, predicatePage, predicateRows } from './predicateCatalog.js';

const emptyDraft = (structure) => ({ field: '', view: predicateViews(structure)[0]?.name ?? '', name: 'equal', args: '', group: 1, groupOperator: 'AND', applyWhenAbsent: false });

export function ReaderPredicateDialog({ api, isOpen, structure, initialRowId = '', formOnly = false, embedded = false, onClose, onApply }) {
  const rows = useMemo(() => predicateRows(structure), [structure]);
  const groups = useMemo(() => predicateGroups(structure, rows), [structure, rows]);
  const compositions = useMemo(() => structure?.predicateCompositions ?? [], [structure]);
  const parameters = useMemo(() => (structure?.declarations ?? []).map((item) => item.parameter).filter((item) => item && String(item.source?.kind).toLowerCase() !== 'output'), [structure]);
  const views = useMemo(() => predicateViews(structure), [structure]);
  const [query, setQuery] = useState('');
  const [mode, setMode] = useState('catalog');
  const [kind, setKind] = useState('all');
  const [family, setFamily] = useState('all');
  const [view, setView] = useState('all');
  const [pageSize, setPageSize] = useState(25);
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState(null);
  const [draft, setDraft] = useState(() => emptyDraft(structure));
  const [saving, setSaving] = useState(false);
  const [savingGroup, setSavingGroup] = useState('');
  const [savingComposition,setSavingComposition]=useState('');
  const [error, setError] = useState('');
  const [confirmRemove, setConfirmRemove] = useState(false);
  const [securityPredicates,setSecurityPredicates]=useState([]);
  const locked = Boolean(selected && selected.predicate?.group === 99);
  const filtered = useMemo(() => filterPredicateRows(rows, { query, kind, family, view }), [rows, query, kind, family, view]);
  const filteredGroups = useMemo(() => filterPredicateGroups(groups, { query, view }), [groups, query, view]);
  const filteredCompositions=useMemo(()=>compositions.filter((item)=>(view==='all'||item.view===view)&&(!query.trim()||`${item.view} ${item.buildKeyword} ${item.terms?.flatMap((term)=>term.groups??[]).join(' ')}`.toLowerCase().includes(query.trim().toLowerCase()))),[compositions,query,view]);
  const paged = useMemo(() => predicatePage(filtered, page, pageSize), [filtered, page, pageSize]);

  const beginAdd = () => { setSelected(null); setConfirmRemove(false); setDraft(emptyDraft(structure)); setError(''); };
  useEffect(() => { if (!isOpen) return; setQuery(''); setMode('catalog'); setKind('all'); setFamily('all'); setView('all'); setPage(1); const initial = rows.find((row) => row.id === initialRowId); if (initial) edit(initial); else beginAdd(); setSaving(false); setSavingGroup(''); }, [isOpen, initialRowId]);
  useEffect(()=>{if(!isOpen||!api)return;let cancelled=false;api.listAuthorizationPredicates({status:'active',limit:500}).then((page)=>{if(!cancelled)setSecurityPredicates((page?.items??[]).filter((item)=>item.linked));}).catch((cause)=>{if(!cancelled)setError(cause.message);});return()=>{cancelled=true;};},[api,isOpen]);
  useEffect(() => { setPage(1); }, [query, kind, family, view, pageSize]);
  const edit = (row) => { setSelected(row); setConfirmRemove(false); setError(''); setDraft({ field: row.field, view: row.view || views[0]?.name || '', expansionViews: row.expansionViews ?? [], name: row.predicate.name, args: (row.predicate.args ?? []).join(', '), group: row.predicate.group, groupOperator: ['AND','OR'].includes(row.groupOperator) ? row.groupOperator : 'AND', applyWhenAbsent: row.predicate?.applyWhenAbsent === true }); };
  const update = (name) => (event) => setDraft((current) => ({ ...current, [name]: event.target.value }));
  const submit = async (event) => {
    event.preventDefault();
    if (locked) { setError('Authorization predicates require the privileged authorization workflow.'); return; }
    const args = draft.args.split(',').map((item) => item.trim()).filter(Boolean);
    if (!draft.field || !draft.view || !draft.name || !Number.isInteger(draft.group) || draft.group < 0 || args.length === 0) { setError('Choose a parameter and view, provide predicate arguments, and use a non-negative group.'); return; }
    setSaving(true); setError('');
    try {
      await onApply({ type: selected ? 'updateFieldPredicate' : 'addFieldPredicate', predicate: { field: draft.field, occurrence: selected?.occurrence ?? 0, view: draft.view, expansionViews: draft.expansionViews?.length ? draft.expansionViews : undefined, group: draft.group, name: draft.name, args, applyWhenAbsent: draft.applyWhenAbsent === true, groupOperator: draft.groupOperator } });
      beginAdd();
    } catch (cause) { setError(cause.message); }
    finally { setSaving(false); }
  };
  const remove = async () => {
    if (!selected) return;
    setSaving(true); setError('');
    try { await onApply({ type: 'removeFieldPredicate', predicate: { field: selected.field, occurrence: selected.occurrence } }); beginAdd(); }
    catch (cause) { setError(cause.message); }
    finally { setSaving(false); }
  };
  const updateGroupOperator = async (group, operator) => {
    if (group.protected || group.unexpanded || group.operator === operator) return;
    setSavingGroup(group.id); setError('');
    try { await onApply({ type: 'updatePredicateGroup', predicateGroup: { group: group.group, views: group.views, operator } }); }
    catch (cause) { setError(cause.message); }
    finally { setSavingGroup(''); }
  };
  const updateComposition=async(composition,terms,buildKeyword)=>{const key=`${composition.view}:${composition.occurrence}`;setSavingComposition(key);setError('');try{await onApply({type:'updatePredicateComposition',predicateComposition:{view:composition.view,occurrence:composition.occurrence,terms,buildKeyword}});}catch(cause){setError(cause.message);}finally{setSavingComposition('');}};

  if (!isOpen) return null;
  const content = <form onSubmit={submit}><DialogBody className="studio-connector-dialog-body">
      {!embedded && <p className="studio-dialog-lead">Search, page, edit, and remove typed predicates. Large readers remain a catalog rather than one oversized form.</p>}
      {error && <Callout intent="danger" role="alert">{error}</Callout>}
      {!formOnly && <><div className="studio-predicate-summary"><Tag minimal intent="primary">{rows.length} predicates</Tag><Tag minimal>{rows.filter((row) => row.kind === 'handler').length} handlers</Tag><Tag minimal icon="lock">{rows.filter((row) => row.predicate?.group === 99).length} authorization</Tag><Tag minimal>{rows.filter((row) => row.family === 'include').length} include</Tag><Tag minimal>{rows.filter((row) => row.family === 'exclude').length} exclude</Tag></div>
      <div className="studio-predicate-mode" role="tablist" aria-label="Predicate workspace"><Button type="button" small active={mode==='catalog'} role="tab" aria-selected={mode==='catalog'} onClick={()=>setMode('catalog')}>All predicates</Button><Button type="button" small active={mode==='groups'} role="tab" aria-selected={mode==='groups'} onClick={()=>setMode('groups')}>Groups</Button></div>
      <div className={`studio-predicate-filters ${mode==='groups'?'group-mode':''}`}><InputGroup leftIcon="search" placeholder={mode==='groups'?'Find group, view, parameter, or handler':'Find parameter, view, source, handler, or column'} value={query} onChange={(event) => setQuery(event.target.value)} rightElement={query?<Button minimal icon="cross" aria-label="Clear predicate search" onClick={()=>setQuery('')}/>:undefined}/><HTMLSelect value={view} onChange={(event) => setView(event.target.value)} aria-label="Target view"><option value="all">All target views</option>{views.map((item)=><option key={item.name} value={item.name}>{item.name}</option>)}</HTMLSelect>{mode==='catalog'&&<><HTMLSelect value={kind} onChange={(event) => setKind(event.target.value)} aria-label="Predicate kind"><option value="all">All kinds</option><option value="sql">SQL predicates</option><option value="handler">Handler predicates</option></HTMLSelect><HTMLSelect value={family} onChange={(event) => setFamily(event.target.value)} aria-label="Predicate family"><option value="all">All families</option><option value="include">Include</option><option value="exclude">Exclude</option><option value="core">Core</option></HTMLSelect><HTMLSelect value={pageSize} onChange={(event) => setPageSize(Number(event.target.value))} aria-label="Rows per page"><option value={25}>25 / page</option><option value={50}>50 / page</option><option value={100}>100 / page</option></HTMLSelect></>}</div>
      {mode==='catalog'?<><div className="studio-predicate-pagination"><span>{paged.total === 0 ? '0' : `${(paged.page - 1) * pageSize + 1}–${Math.min(paged.page * pageSize, paged.total)}`} of {paged.total}</span><ButtonGroup minimal><Button type="button" small icon="chevron-left" aria-label="Previous predicate page" disabled={paged.page === 1} onClick={() => setPage((value) => Math.max(1, value - 1))} /><span>Page {paged.page} of {paged.pages}</span><Button type="button" small icon="chevron-right" aria-label="Next predicate page" disabled={paged.page === paged.pages} onClick={() => setPage((value) => Math.min(paged.pages, value + 1))} /></ButtonGroup></div>
      <div className="studio-predicate-table-wrap"><HTMLTable striped interactive className="studio-data-table studio-predicate-table"><thead><tr><th>Parameter</th><th>Target views</th><th>Predicate</th><th>Arguments / handler</th><th>Group</th></tr></thead><tbody>{paged.items.map((row) => <tr key={row.id} className={selected?.id === row.id ? 'studio-selected-row' : ''}><td><button type="button" className="studio-cell-button" onClick={() => edit(row)}><strong>{row.field}</strong><small className="studio-tree-meta">{row.source}</small></button></td><td><code>{(row.expansionViews??[row.view]).filter(Boolean).join(', ')||'—'}</code></td><td><Tag minimal intent={row.kind === 'handler' ? 'warning' : 'none'} icon={row.predicate?.group === 99 ? 'lock' : undefined}>{row.predicate.name}</Tag></td><td><code>{(row.predicate.args ?? []).join(', ')}</code></td><td><strong>{row.predicate.group}</strong><small className="studio-tree-meta">{row.groupOperator}</small></td></tr>)}</tbody></HTMLTable>{paged.items.length === 0 && <div className="studio-empty-compact">No predicates match these filters.</div>}</div></>:<PredicateGroupComposer groups={filteredGroups} compositions={filteredCompositions} savingGroup={savingGroup} savingComposition={savingComposition} onEdit={edit} onOperator={updateGroupOperator} onComposition={updateComposition}/>}
      </>}
      <div className="studio-panel-heading studio-predicate-form-heading"><div><h3>{locked ? `Authorization · ${selected.field}` : selected ? `Edit ${selected.field}` : 'Add predicate'}</h3><p className="studio-muted">Group 99 is reserved for required authorization and cannot be changed through ordinary filter authoring.</p></div>{selected && <ButtonGroup minimal><Button type="button" small icon="add" onClick={beginAdd}>New</Button>{!locked && <Button type="button" small icon="trash" intent="danger" onClick={() => setConfirmRemove(true)}>Remove</Button>}</ButtonGroup>}</div>
      {locked && <Callout intent="warning" icon="lock" title="Authorization predicate is protected">Use the privileged authorization workflow to change required scope. Optional filters cannot broaden or replace this predicate.</Callout>}
      <div className="studio-form-grid"><FormGroup label="Parameter" labelFor="predicate-field" required>{selected ? <InputGroup id="predicate-field" value={draft.field} disabled /> : <><InputGroup id="predicate-field" list="predicate-parameter-options" value={draft.field} onChange={update('field')} placeholder="Search parameter" disabled={saving} /><datalist id="predicate-parameter-options">{parameters.map((parameter) => <option value={parameter.name} key={parameter.name}>{parameter.source?.name}</option>)}</datalist></>}</FormGroup><FormGroup label="Target view" labelFor="predicate-view" helperText={selected&&draft.expansionViews?.length>1?`Shared by ${draft.expansionViews.join(', ')}. Group targeting is preserved while editing.`:selected?'Group targeting is preserved while editing.':undefined} required><HTMLSelect id="predicate-view" value={draft.view} onChange={update('view')} fill disabled={saving || locked || Boolean(selected)}>{views.map((view) => <option value={view.name} key={view.name}>{view.name}</option>)}</HTMLSelect></FormGroup></div>
      {!selected&&<FormGroup label="Security predicate" labelFor="security-predicate" helperText="Assign a linked Security predicate to this parameter. Alias and columns are informational hints from its catalog entry."><HTMLSelect id="security-predicate" fill value="" disabled={saving} onChange={(event)=>{const item=securityPredicates.find((predicate)=>predicate.name===event.target.value);if(item)setDraft((current)=>({...current,name:'handler',args:`${item.packagePath}.${item.typeName}`,group:99,applyWhenAbsent:true}));}}><option value="">Use an ordinary SQL predicate</option>{securityPredicates.map((predicate)=><option key={predicate.name} value={predicate.name}>{predicate.title}{predicate.alias?` · ${predicate.alias}.${(predicate.columns??[]).join(',')}`:''}</option>)}</HTMLSelect></FormGroup>}
      <div className="studio-form-grid"><FormGroup label="Predicate" labelFor="predicate-name" required><InputGroup id="predicate-name" value={draft.name} onChange={update('name')} disabled={saving || locked} /></FormGroup><FormGroup label="Group" labelFor="predicate-group" required><NumericInput id="predicate-group" value={draft.group} min={0} fill onValueChange={(group) => setDraft((current) => ({ ...current, group }))} disabled={saving || locked} /></FormGroup></div>
      <FormGroup label="Predicate arguments" labelFor="predicate-args" helperText="Comma-separated SQL namespace/column or handler identity." required><InputGroup id="predicate-args" value={draft.args} onChange={update('args')} disabled={saving || locked} /></FormGroup>
      <div className="studio-form-grid"><FormGroup label="Within-group operator" labelFor="predicate-group-operator" helperText="Applied by Datly when compiling this filter group."><HTMLSelect id="predicate-group-operator" value={draft.groupOperator} onChange={update('groupOperator')} fill disabled={saving || locked || Boolean(selected)}><option value="AND">AND</option><option value="OR">OR</option></HTMLSelect></FormGroup><FormGroup label="When input is absent" labelFor="predicate-when-absent" helperText="Ordinary predicates are skipped when their input is absent."><HTMLSelect id="predicate-when-absent" value={String(draft.applyWhenAbsent)} onChange={(event)=>setDraft((current)=>({...current,applyWhenAbsent:event.target.value==='true'}))} fill disabled={saving || locked}><option value="false">Skip predicate</option><option value="true">Apply predicate</option></HTMLSelect></FormGroup></div>
      {confirmRemove && <Callout intent="danger" title={`Remove predicate from ${selected?.field}?`}><p>The reader will be recompiled before this revision is accepted.</p><Button type="button" intent="danger" icon="trash" loading={saving} onClick={remove}>Confirm removal</Button></Callout>}
    </DialogBody><DialogFooter actions={<><Button onClick={onClose} disabled={saving}>{embedded ? 'Back to predicates' : 'Close'}</Button><Button type="submit" intent="primary" disabled={locked} loading={saving}>{selected ? 'Save predicate' : 'Add predicate'}</Button></>} /></form>;
  return embedded ? <Card className="studio-card studio-columns-panel studio-inline-contract-form" elevation={0}>{content}</Card> : <Dialog className="studio-connector-dialog studio-predicate-dialog" isOpen={isOpen} onClose={onClose} title="Predicate catalog" icon="filter" canOutsideClickClose={!saving}>{content}</Dialog>;
}

function PredicateGroupComposer({groups,compositions,savingGroup,savingComposition,onEdit,onOperator,onComposition}) {
  const [expanded,setExpanded]=useState(()=>new Set());
  if(groups.length===0&&(compositions??[]).length===0)return <div className="studio-empty-compact">No predicate groups match this view or search.</div>;
  return <div className="studio-predicate-groups"><Callout compact intent="primary" title="Compiled Boolean contract">Within-group controls edit FilterGroup AND/OR. Composition stages below edit CombineAnd/CombineOr, persistent connectors, and WHERE/AND emission without inferring semantics from group numbers.</Callout>{(compositions??[]).map((composition)=><PredicateCompositionEditor key={`${composition.view}:${composition.occurrence}`} composition={composition} saving={savingComposition===`${composition.view}:${composition.occurrence}`} onSave={onComposition}/>)}{groups.map((group)=>{const showMembers=group.predicates.length<=10||expanded.has(group.id);return <section key={group.id} className={`studio-predicate-group ${group.protected?'protected':''}`} aria-label={`Predicate group ${group.group}`}><div className="studio-predicate-group-heading"><div><strong>Group {group.group}</strong><span>{group.predicates.length} {group.predicates.length===1?'predicate':'predicates'} · {group.views.length} {group.views.length===1?'view':'views'}</span></div><div>{group.protected&&<Tag minimal icon="lock">Protected</Tag>}{group.ambiguous&&<Tag minimal intent="warning">Mixed operators</Tag>}{group.unexpanded?<Tag minimal intent="warning">Not applied</Tag>:<ButtonGroup minimal aria-label={`Within-group operator for group ${group.group}`}><Button type="button" small active={group.operator==='AND'} disabled={group.protected||Boolean(savingGroup)} loading={savingGroup===group.id&&group.operator!=='AND'} onClick={()=>onOperator(group,'AND')}>AND</Button><Button type="button" small active={group.operator==='OR'} disabled={group.protected||Boolean(savingGroup)} loading={savingGroup===group.id&&group.operator!=='OR'} onClick={()=>onOperator(group,'OR')}>OR</Button></ButtonGroup>}</div></div><div className="studio-predicate-group-scope"><span>Expansion scope</span><code>{group.views.join(' · ')||'No compiled expansion'}</code></div>{group.predicates.length>10&&<Button type="button" minimal small className="studio-predicate-group-toggle" icon={showMembers?'chevron-up':'chevron-down'} onClick={()=>setExpanded((current)=>{const next=new Set(current);if(next.has(group.id))next.delete(group.id);else next.add(group.id);return next;})}>{showMembers?'Hide predicates':`Show ${group.predicates.length} predicates`}</Button>}{showMembers&&<div className="studio-predicate-group-members">{group.predicates.length===0?<span className="studio-muted">This group currently emits no predicate SQL.</span>:group.predicates.map((row)=><button type="button" key={`${group.id}:${row.id}`} onClick={()=>onEdit(row)}><span><strong>{row.field}</strong><small>{row.source}</small></span><Tag minimal intent={row.kind==='handler'?'warning':'none'}>{row.predicate.name}</Tag><code>{(row.predicate.args??[]).join(', ')}</code>{row.predicate?.applyWhenAbsent&&<Tag minimal intent="primary">when absent</Tag>}</button>)}</div>}</section>;})}</div>;
}

function PredicateCompositionEditor({composition,saving,onSave}){const [terms,setTerms]=useState(()=>cloneTerms(composition.terms));const [keyword,setKeyword]=useState(composition.buildKeyword||'');useEffect(()=>{setTerms(cloneTerms(composition.terms));setKeyword(composition.buildKeyword||'');},[composition]);const protectedGroup=terms.some((term)=>term.groups?.includes(99));const updateTerm=(index,field,value)=>setTerms((current)=>current.map((term,position)=>position===index?{...term,[field]:value}:term));const dirty=JSON.stringify(terms)!==JSON.stringify(composition.terms??[])||keyword!==(composition.buildKeyword||'');return <section className="studio-predicate-composition" aria-label={`${composition.view} predicate composition ${composition.occurrence+1}`}><div className="studio-predicate-group-heading"><div><strong>{composition.view} Boolean composition</strong><span>Chain {composition.occurrence+1}</span></div>{composition.editable?<Tag minimal intent="success">source-preserving</Tag>:<Tag minimal intent="warning">read only</Tag>}</div>{!composition.editable&&<Callout compact intent="warning">{composition.reason||'This expression uses unsupported nested composition and is not editable.'}</Callout>}<div className="studio-predicate-composition-terms">{terms.map((term,index)=><div key={`${index}-${term.groups?.join('-')}`}><span>Stage {index+1}</span><HTMLSelect aria-label={`Connector for stage ${index+1}`} value={term.connector||'AND'} onChange={(event)=>updateTerm(index,'connector',event.target.value)} disabled={!composition.editable||saving||protectedGroup}><option value="AND">AND with prior</option><option value="OR">OR with prior</option></HTMLSelect><HTMLSelect aria-label={`Combine operator for stage ${index+1}`} value={term.operator||'AND'} onChange={(event)=>updateTerm(index,'operator',event.target.value)} disabled={!composition.editable||saving||(term.groups??[]).includes(99)}><option value="AND">Combine groups with AND</option><option value="OR">Combine groups with OR</option></HTMLSelect><code>{(term.groups??[]).map((group)=>`Group ${group}`).join(' · ')}</code></div>)}</div><div className="studio-predicate-composition-footer"><FormGroup label="SQL attachment" labelFor={`composition-build-${composition.view}-${composition.occurrence}`}><HTMLSelect id={`composition-build-${composition.view}-${composition.occurrence}`} value={keyword} onChange={(event)=>setKeyword(event.target.value)} disabled={!composition.editable||saving}><option value="WHERE">Build WHERE</option><option value="AND">Build AND</option><option value="">No keyword</option></HTMLSelect></FormGroup><Button type="button" intent="primary" icon="floppy-disk" loading={saving} disabled={!composition.editable||!dirty} onClick={()=>onSave(composition,terms,keyword)}>Save composition</Button></div></section>;}
function cloneTerms(terms){return(terms??[]).map((term)=>({...term,groups:[...(term.groups??[])]}));}

function predicateViews(structure) {
  const result = [];
  const visit = (view) => { const name = view?.namespace || view?.name; if (name && !result.some((item) => item.name === name)) result.push({ name }); for (const relation of view?.relations ?? []) visit(relation.view); };
  visit(structure?.component?.rootView);
  for (const view of structure?.views ?? []) if (view?.name && !result.some((item) => item.name === view.name)) result.push(view);
  return result;
}
