PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS CI_VENDOR (
    ID INTEGER PRIMARY KEY,
    VENDOR_NAME TEXT NOT NULL,
    PARENT_COMPANY TEXT,
    CATEGORY TEXT,
    PRIMARY_PURPOSE TEXT,
    IAB_GVL_STATUS TEXT
);

CREATE TABLE IF NOT EXISTS CI_VENDOR_DOMAIN (
    ID INTEGER PRIMARY KEY,
    VENDOR_ID INTEGER NOT NULL,
    DOMAIN TEXT NOT NULL,
    FOREIGN KEY (VENDOR_ID) REFERENCES CI_VENDOR(ID)
);

CREATE TABLE IF NOT EXISTS CI_CHANNEL_V2 (ID INTEGER PRIMARY KEY, NAME TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS CI_PUBLISHER (ID INTEGER PRIMARY KEY, NAME TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS CI_SITE (ID INTEGER PRIMARY KEY, NAME TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS CI_CARRIER_ALIAS (ID INTEGER PRIMARY KEY, NAME TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS CI_COUNTRY_REGION (
    COUNTRY_CODE TEXT NOT NULL,
    COUNTRY_NAME TEXT NOT NULL,
    REGION_CODE TEXT NOT NULL,
    REGION_NAME TEXT NOT NULL,
    PRIMARY KEY (COUNTRY_CODE, REGION_CODE)
);
CREATE TABLE IF NOT EXISTS CI_DMA (ID INTEGER PRIMARY KEY, NAME TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS CI_AGEGROUP (ID INTEGER PRIMARY KEY, NAME TEXT NOT NULL);

INSERT OR REPLACE INTO CI_VENDOR (ID, VENDOR_NAME, PARENT_COMPANY, CATEGORY, PRIMARY_PURPOSE, IAB_GVL_STATUS) VALUES
    (900001, 'Northwind Media', 'Northwind', 'Advertising', 'Measurement', 'registered'),
    (900002, 'Contoso Audiences', 'Contoso', 'Data', 'Audience enrichment', 'registered'),
    (900003, 'Fabrikam Exchange', 'Fabrikam', 'Advertising', 'Inventory', 'pending');

INSERT OR REPLACE INTO CI_VENDOR_DOMAIN (ID, VENDOR_ID, DOMAIN) VALUES
    (1, 900001, 'northwind.example'),
    (2, 900001, 'metrics.northwind.example'),
    (3, 900002, 'contoso.example'),
    (4, 900003, 'fabrikam.example');

INSERT OR REPLACE INTO CI_CHANNEL_V2 (ID, NAME) VALUES (1, 'Display'), (2, 'Video');
INSERT OR REPLACE INTO CI_PUBLISHER (ID, NAME) VALUES (1, 'Example Publisher');
INSERT OR REPLACE INTO CI_SITE (ID, NAME) VALUES (1, 'example.test');
INSERT OR REPLACE INTO CI_CARRIER_ALIAS (ID, NAME) VALUES (1, 'Example Carrier');
INSERT OR REPLACE INTO CI_COUNTRY_REGION (COUNTRY_CODE, COUNTRY_NAME, REGION_CODE, REGION_NAME) VALUES ('US', 'United States', 'CA', 'California');
INSERT OR REPLACE INTO CI_DMA (ID, NAME) VALUES (803, 'Los Angeles');
INSERT OR REPLACE INTO CI_AGEGROUP (ID, NAME) VALUES (1, '18-24');
