PRAGMA foreign_keys = ON;

CREATE TABLE VENDOR (
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    ACCOUNT_ID INTEGER NOT NULL,
    CREATED DATETIME NOT NULL,
    USER_CREATED INTEGER NOT NULL,
    UPDATED DATETIME,
    USER_UPDATED INTEGER
);

CREATE TABLE PRODUCT (
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    VENDOR_ID INTEGER NOT NULL,
    CREATED DATETIME NOT NULL,
    STATUS INTEGER NOT NULL,
    USER_CREATED INTEGER NOT NULL,
    UPDATED DATETIME,
    USER_UPDATED INTEGER,
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(ID)
);
