// Code generated by datly link sync. Additive only.
package accesspredicate

import "reflect"

var _datlyReachableNamespaceAccess = reflect.TypeFor[NamespaceAccess]()
var _datlyReachableNamespaceDirectory = reflect.TypeFor[NamespaceDirectory]()

func init() {}
