// Code generated by datly link sync. Additive only.
package accesscontext

import "reflect"

var _datlyReachablecodecFactory = reflect.TypeFor[codecFactory]()

var _datlyReachableentityIDs = reflect.TypeFor[entityIDs]()

func init() {}
