package dependencylink

import (
	_ "github.com/viant/datly-studio/studio/auth/reader"
	_ "github.com/viant/datly-studio/studio/authorization"
	_ "github.com/viant/datly-studio/studio/bff_sessions/reader"
	_ "github.com/viant/datly-studio/studio/bff_sessions/writer"
	_ "github.com/viant/datly-studio/studio/connectors/reader"
	_ "github.com/viant/datly-studio/studio/connectors/writer"
	_ "github.com/viant/datly-studio/studio/namespaces/reader"
	_ "github.com/viant/datly-studio/studio/namespaces/writer"
	_ "github.com/viant/datly-studio/studio/report_acl/reader"
	_ "github.com/viant/datly-studio/studio/report_acl/writer"
	_ "github.com/viant/datly-studio/studio/report_cube_configs/reader"
	_ "github.com/viant/datly-studio/studio/report_cube_configs/writer"
	_ "github.com/viant/datly-studio/studio/report_mcp_exposures/reader"
	_ "github.com/viant/datly-studio/studio/report_mcp_exposures/writer"
	_ "github.com/viant/datly-studio/studio/report_parameters/reader"
	_ "github.com/viant/datly-studio/studio/report_parameters/writer"
	_ "github.com/viant/datly-studio/studio/report_publication_events/reader"
	_ "github.com/viant/datly-studio/studio/report_publications/reader"
	_ "github.com/viant/datly-studio/studio/report_publications/writer"
	_ "github.com/viant/datly-studio/studio/report_resource_files/reader"
	_ "github.com/viant/datly-studio/studio/report_resource_files/writer"
	_ "github.com/viant/datly-studio/studio/report_resource_folders/reader"
	_ "github.com/viant/datly-studio/studio/report_resource_folders/writer"
	_ "github.com/viant/datly-studio/studio/report_skill_roots/reader"
	_ "github.com/viant/datly-studio/studio/report_skill_roots/writer"
	_ "github.com/viant/datly-studio/studio/report_versions/reader"
	_ "github.com/viant/datly-studio/studio/report_versions/writer"
	_ "github.com/viant/datly-studio/studio/report_views/reader"
	_ "github.com/viant/datly-studio/studio/report_warmup_runs/reader"
	_ "github.com/viant/datly-studio/studio/reports/catalogpredicate"
	_ "github.com/viant/datly-studio/studio/reports/get"
	_ "github.com/viant/datly-studio/studio/reports/reader"
	_ "github.com/viant/datly-studio/studio/reports/writer"
	_ "github.com/viant/datly-studio/studio/runtime_generations/reader"
	_ "github.com/viant/datly-studio/studio/runtime_generations/writer"
)

func init() {}
