CREATE TABLE VENDOR (
    ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ACCOUNT_ID INT NOT NULL,
    CREATED DATETIME NOT NULL,
    USER_CREATED INT NOT NULL,
    UPDATED DATETIME NULL,
    USER_UPDATED INT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PRODUCT (
    ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VENDOR_ID INT NOT NULL,
    CREATED DATETIME NOT NULL,
    STATUS INT NOT NULL,
    USER_CREATED INT NOT NULL,
    UPDATED DATETIME NULL,
    USER_UPDATED INT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_product_vendor FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
