// Package studioopenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package studioopenapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Wire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c defines model for Wire_3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c.
type Wire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c struct {
	CanEdit     bool    `json:"canEdit"`
	CanPublish  bool    `json:"canPublish"`
	CanRun      bool    `json:"canRun"`
	CanUseDql   bool    `json:"canUseDql"`
	CanView     bool    `json:"canView"`
	Etag        *int64  `json:"etag"`
	ReportId    *string `json:"reportId"`
	SubjectId   *string `json:"subjectId"`
	SubjectType *string `json:"subjectType"`
}

// Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a defines model for Wire_38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a.
type Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a struct {
	Items  *[]Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item `json:"items"`
	Limit  int64                                                                              `json:"limit"`
	Offset int64                                                                              `json:"offset"`
}

// Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1 defines model for Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a.Items.1.
type Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1 = map[string]interface{}

// Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item defines model for Wire_38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a.items.Item.
type Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item struct {
	union json.RawMessage
}

// Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c defines model for Wire_95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c.
type Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c struct {
	Items *[]Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item `json:"items"`
}

// Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1 defines model for Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c.Items.1.
type Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1 = map[string]interface{}

// Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item defines model for Wire_95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c.items.Item.
type Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item struct {
	union json.RawMessage
}

// WireB42a7344fc0606034fc05c388a62f83c484228cb1e9be8bf4055ff09f8f4a044 defines model for Wire_b42a7344fc0606034fc05c388a62f83c484228cb1e9be8bf4055ff09f8f4a044.
type WireB42a7344fc0606034fc05c388a62f83c484228cb1e9be8bf4055ff09f8f4a044 struct {
	ComponentName        string    `json:"componentName"`
	ComponentScope       string    `json:"componentScope"`
	CreatedAt            time.Time `json:"createdAt"`
	CurrentDraftVersion  *int64    `json:"currentDraftVersion,omitempty"`
	DefaultConnectorName string    `json:"defaultConnectorName"`
	Description          *string   `json:"description,omitempty"`
	Etag                 int64     `json:"etag"`
	Id                   string    `json:"id"`
	Namespace            string    `json:"namespace"`
	OwnerId              string    `json:"ownerId"`
	OwnerPackage         string    `json:"ownerPackage"`
	Slug                 string    `json:"slug"`
	Status               string    `json:"status"`
	Title                string    `json:"title"`
	UpdatedAt            time.Time `json:"updatedAt"`
}

// WireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c defines model for Wire_bba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c.
type WireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c struct {
	ComponentName        string    `json:"componentName"`
	ComponentScope       string    `json:"componentScope"`
	CreatedAt            time.Time `json:"createdAt"`
	CurrentDraftVersion  *int64    `json:"currentDraftVersion,omitempty"`
	DefaultConnectorName string    `json:"defaultConnectorName"`
	Description          *string   `json:"description,omitempty"`
	Etag                 int64     `json:"etag"`
	Id                   string    `json:"id"`
	Namespace            string    `json:"namespace"`
	OwnerId              string    `json:"ownerId"`
	OwnerPackage         string    `json:"ownerPackage"`
	Slug                 string    `json:"slug"`
	Status               string    `json:"status"`
	Title                string    `json:"title"`
	UpdatedAt            time.Time `json:"updatedAt"`
}

// POSTv1studiosdkaclListJSONBody defines parameters for POSTv1studiosdkaclList.
type POSTv1studiosdkaclListJSONBody struct {
	ReportId string `json:"reportId"`
}

// POSTv1studiosdkaclListParams defines parameters for POSTv1studiosdkaclList.
type POSTv1studiosdkaclListParams struct {
	SubjectType *string `form:"subjectType,omitempty" json:"subjectType,omitempty"`
	SubjectId   *string `form:"subjectId,omitempty" json:"subjectId,omitempty"`
}

// POSTv1studiosdkreportsGetJSONBody defines parameters for POSTv1studiosdkreportsGet.
type POSTv1studiosdkreportsGetJSONBody struct {
	Id string `json:"id"`
}

// POSTv1studiosdkreportsListJSONBody defines parameters for POSTv1studiosdkreportsList.
type POSTv1studiosdkreportsListJSONBody struct {
	ConnectorName *string   `json:"connectorName,omitempty"`
	Fields        *[]string `json:"fields,omitempty"`
	Limit         *int64    `json:"limit,omitempty"`
	Namespace     *string   `json:"namespace,omitempty"`
	Offset        *int64    `json:"offset,omitempty"`
	OrderBy       *string   `json:"orderBy,omitempty"`
	OwnerId       *string   `json:"ownerId,omitempty"`
	Query         *string   `json:"query,omitempty"`
	Status        *string   `json:"status,omitempty"`
}

// POSTv1studiosdkaclListJSONRequestBody defines body for POSTv1studiosdkaclList for application/json ContentType.
type POSTv1studiosdkaclListJSONRequestBody POSTv1studiosdkaclListJSONBody

// POSTv1studiosdkreportsGetJSONRequestBody defines body for POSTv1studiosdkreportsGet for application/json ContentType.
type POSTv1studiosdkreportsGetJSONRequestBody POSTv1studiosdkreportsGetJSONBody

// POSTv1studiosdkreportsListJSONRequestBody defines body for POSTv1studiosdkreportsList for application/json ContentType.
type POSTv1studiosdkreportsListJSONRequestBody POSTv1studiosdkreportsListJSONBody

// AsWireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c returns the union data inside the Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item as a WireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c
func (t Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item) AsWireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c() (WireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c, error) {
	var body WireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c overwrites any union data inside the Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item as the provided WireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c
func (t *Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item) FromWireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c(v WireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c performs a merge with any union data inside the Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item, using the provided WireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c
func (t *Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item) MergeWireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c(v WireBba07f0bad61cd85885417e1c20c5cff98c1ebf3abb205fd71b51c6069ea161c) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1 returns the union data inside the Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item as a Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1
func (t Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item) AsWire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1() (Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1, error) {
	var body Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1 overwrites any union data inside the Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item as the provided Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1
func (t *Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item) FromWire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1(v Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1 performs a merge with any union data inside the Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item, using the provided Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1
func (t *Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item) MergeWire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1(v Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649aItems1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a_Items_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsWire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c returns the union data inside the Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item as a Wire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c
func (t Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item) AsWire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c() (Wire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c, error) {
	var body Wire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c overwrites any union data inside the Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item as the provided Wire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c
func (t *Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item) FromWire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c(v Wire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c performs a merge with any union data inside the Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item, using the provided Wire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c
func (t *Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item) MergeWire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c(v Wire3260fb4c4c3ba7c084402fa64664f099dae40719e64a304feae0d1fd05cf8c6c) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1 returns the union data inside the Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item as a Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1
func (t Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item) AsWire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1() (Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1, error) {
	var body Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1 overwrites any union data inside the Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item as the provided Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1
func (t *Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item) FromWire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1(v Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1 performs a merge with any union data inside the Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item, using the provided Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1
func (t *Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item) MergeWire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1(v Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35cItems1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c_Items_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// POSTv1studiosdkaclListWithBody acl
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/studio/sdk/acl.list (the `POSTv1studiosdkaclList` operationId).
	POSTv1studiosdkaclListWithBody(ctx context.Context, params *POSTv1studiosdkaclListParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// POSTv1studiosdkaclList acl
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/studio/sdk/acl.list (the `POSTv1studiosdkaclList` operationId).
	POSTv1studiosdkaclList(ctx context.Context, params *POSTv1studiosdkaclListParams, body POSTv1studiosdkaclListJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// POSTv1studiosdkreportsGetWithBody report
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/studio/sdk/reports.get (the `POSTv1studiosdkreportsGet` operationId).
	POSTv1studiosdkreportsGetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// POSTv1studiosdkreportsGet report
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/studio/sdk/reports.get (the `POSTv1studiosdkreportsGet` operationId).
	POSTv1studiosdkreportsGet(ctx context.Context, body POSTv1studiosdkreportsGetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// POSTv1studiosdkreportsListWithBody report
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/studio/sdk/reports.list (the `POSTv1studiosdkreportsList` operationId).
	POSTv1studiosdkreportsListWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// POSTv1studiosdkreportsList report
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/studio/sdk/reports.list (the `POSTv1studiosdkreportsList` operationId).
	POSTv1studiosdkreportsList(ctx context.Context, body POSTv1studiosdkreportsListJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// POSTv1studiosdkaclListWithBody acl
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/studio/sdk/acl.list (the `POSTv1studiosdkaclList` operationId).
func (c *Client) POSTv1studiosdkaclListWithBody(ctx context.Context, params *POSTv1studiosdkaclListParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTv1studiosdkaclListRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// POSTv1studiosdkaclList acl
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/studio/sdk/acl.list (the `POSTv1studiosdkaclList` operationId).
func (c *Client) POSTv1studiosdkaclList(ctx context.Context, params *POSTv1studiosdkaclListParams, body POSTv1studiosdkaclListJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTv1studiosdkaclListRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// POSTv1studiosdkreportsGetWithBody report
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/studio/sdk/reports.get (the `POSTv1studiosdkreportsGet` operationId).
func (c *Client) POSTv1studiosdkreportsGetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTv1studiosdkreportsGetRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// POSTv1studiosdkreportsGet report
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/studio/sdk/reports.get (the `POSTv1studiosdkreportsGet` operationId).
func (c *Client) POSTv1studiosdkreportsGet(ctx context.Context, body POSTv1studiosdkreportsGetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTv1studiosdkreportsGetRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// POSTv1studiosdkreportsListWithBody report
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/studio/sdk/reports.list (the `POSTv1studiosdkreportsList` operationId).
func (c *Client) POSTv1studiosdkreportsListWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTv1studiosdkreportsListRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// POSTv1studiosdkreportsList report
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/studio/sdk/reports.list (the `POSTv1studiosdkreportsList` operationId).
func (c *Client) POSTv1studiosdkreportsList(ctx context.Context, body POSTv1studiosdkreportsListJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPOSTv1studiosdkreportsListRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPOSTv1studiosdkaclListRequest calls the generic POSTv1studiosdkaclList builder with application/json body
func NewPOSTv1studiosdkaclListRequest(server string, params *POSTv1studiosdkaclListParams, body POSTv1studiosdkaclListJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPOSTv1studiosdkaclListRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPOSTv1studiosdkaclListRequestWithBody constructs an http.Request for the POSTv1studiosdkaclList method, with any body, and a specified content type
func NewPOSTv1studiosdkaclListRequestWithBody(server string, params *POSTv1studiosdkaclListParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/studio/sdk/acl.list")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.SubjectType != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "subjectType", *params.SubjectType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SubjectId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "subjectId", *params.SubjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPOSTv1studiosdkreportsGetRequest calls the generic POSTv1studiosdkreportsGet builder with application/json body
func NewPOSTv1studiosdkreportsGetRequest(server string, body POSTv1studiosdkreportsGetJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPOSTv1studiosdkreportsGetRequestWithBody(server, "application/json", bodyReader)
}

// NewPOSTv1studiosdkreportsGetRequestWithBody constructs an http.Request for the POSTv1studiosdkreportsGet method, with any body, and a specified content type
func NewPOSTv1studiosdkreportsGetRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/studio/sdk/reports.get")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPOSTv1studiosdkreportsListRequest calls the generic POSTv1studiosdkreportsList builder with application/json body
func NewPOSTv1studiosdkreportsListRequest(server string, body POSTv1studiosdkreportsListJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPOSTv1studiosdkreportsListRequestWithBody(server, "application/json", bodyReader)
}

// NewPOSTv1studiosdkreportsListRequestWithBody constructs an http.Request for the POSTv1studiosdkreportsList method, with any body, and a specified content type
func NewPOSTv1studiosdkreportsListRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/studio/sdk/reports.list")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// POSTv1studiosdkaclListWithBodyWithResponse acl
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/studio/sdk/acl.list (the `POSTv1studiosdkaclList` operationId).
	POSTv1studiosdkaclListWithBodyWithResponse(ctx context.Context, params *POSTv1studiosdkaclListParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTv1studiosdkaclListResponse, error)

	// POSTv1studiosdkaclListWithResponse acl
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/studio/sdk/acl.list (the `POSTv1studiosdkaclList` operationId).
	POSTv1studiosdkaclListWithResponse(ctx context.Context, params *POSTv1studiosdkaclListParams, body POSTv1studiosdkaclListJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTv1studiosdkaclListResponse, error)

	// POSTv1studiosdkreportsGetWithBodyWithResponse report
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/studio/sdk/reports.get (the `POSTv1studiosdkreportsGet` operationId).
	POSTv1studiosdkreportsGetWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTv1studiosdkreportsGetResponse, error)

	// POSTv1studiosdkreportsGetWithResponse report
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/studio/sdk/reports.get (the `POSTv1studiosdkreportsGet` operationId).
	POSTv1studiosdkreportsGetWithResponse(ctx context.Context, body POSTv1studiosdkreportsGetJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTv1studiosdkreportsGetResponse, error)

	// POSTv1studiosdkreportsListWithBodyWithResponse report
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/studio/sdk/reports.list (the `POSTv1studiosdkreportsList` operationId).
	POSTv1studiosdkreportsListWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTv1studiosdkreportsListResponse, error)

	// POSTv1studiosdkreportsListWithResponse report
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/studio/sdk/reports.list (the `POSTv1studiosdkreportsList` operationId).
	POSTv1studiosdkreportsListWithResponse(ctx context.Context, body POSTv1studiosdkreportsListJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTv1studiosdkreportsListResponse, error)
}

type POSTv1studiosdkaclListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r POSTv1studiosdkaclListResponse) GetJSON200() *Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r POSTv1studiosdkaclListResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r POSTv1studiosdkaclListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r POSTv1studiosdkaclListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r POSTv1studiosdkaclListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type POSTv1studiosdkreportsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *WireB42a7344fc0606034fc05c388a62f83c484228cb1e9be8bf4055ff09f8f4a044
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r POSTv1studiosdkreportsGetResponse) GetJSON200() *WireB42a7344fc0606034fc05c388a62f83c484228cb1e9be8bf4055ff09f8f4a044 {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r POSTv1studiosdkreportsGetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r POSTv1studiosdkreportsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r POSTv1studiosdkreportsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r POSTv1studiosdkreportsGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type POSTv1studiosdkreportsListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r POSTv1studiosdkreportsListResponse) GetJSON200() *Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r POSTv1studiosdkreportsListResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r POSTv1studiosdkreportsListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r POSTv1studiosdkreportsListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r POSTv1studiosdkreportsListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// POSTv1studiosdkaclListWithBodyWithResponse acl
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/studio/sdk/acl.list (the `POSTv1studiosdkaclList` operationId).
func (c *ClientWithResponses) POSTv1studiosdkaclListWithBodyWithResponse(ctx context.Context, params *POSTv1studiosdkaclListParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTv1studiosdkaclListResponse, error) {
	rsp, err := c.POSTv1studiosdkaclListWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTv1studiosdkaclListResponse(rsp)
}

// POSTv1studiosdkaclListWithResponse acl
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/studio/sdk/acl.list (the `POSTv1studiosdkaclList` operationId).
func (c *ClientWithResponses) POSTv1studiosdkaclListWithResponse(ctx context.Context, params *POSTv1studiosdkaclListParams, body POSTv1studiosdkaclListJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTv1studiosdkaclListResponse, error) {
	rsp, err := c.POSTv1studiosdkaclList(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTv1studiosdkaclListResponse(rsp)
}

// POSTv1studiosdkreportsGetWithBodyWithResponse report
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/studio/sdk/reports.get (the `POSTv1studiosdkreportsGet` operationId).
func (c *ClientWithResponses) POSTv1studiosdkreportsGetWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTv1studiosdkreportsGetResponse, error) {
	rsp, err := c.POSTv1studiosdkreportsGetWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTv1studiosdkreportsGetResponse(rsp)
}

// POSTv1studiosdkreportsGetWithResponse report
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/studio/sdk/reports.get (the `POSTv1studiosdkreportsGet` operationId).
func (c *ClientWithResponses) POSTv1studiosdkreportsGetWithResponse(ctx context.Context, body POSTv1studiosdkreportsGetJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTv1studiosdkreportsGetResponse, error) {
	rsp, err := c.POSTv1studiosdkreportsGet(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTv1studiosdkreportsGetResponse(rsp)
}

// POSTv1studiosdkreportsListWithBodyWithResponse report
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/studio/sdk/reports.list (the `POSTv1studiosdkreportsList` operationId).
func (c *ClientWithResponses) POSTv1studiosdkreportsListWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*POSTv1studiosdkreportsListResponse, error) {
	rsp, err := c.POSTv1studiosdkreportsListWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTv1studiosdkreportsListResponse(rsp)
}

// POSTv1studiosdkreportsListWithResponse report
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/studio/sdk/reports.list (the `POSTv1studiosdkreportsList` operationId).
func (c *ClientWithResponses) POSTv1studiosdkreportsListWithResponse(ctx context.Context, body POSTv1studiosdkreportsListJSONRequestBody, reqEditors ...RequestEditorFn) (*POSTv1studiosdkreportsListResponse, error) {
	rsp, err := c.POSTv1studiosdkreportsList(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePOSTv1studiosdkreportsListResponse(rsp)
}

// ParsePOSTv1studiosdkaclListResponse parses an HTTP response from a POSTv1studiosdkaclListWithResponse call
func ParsePOSTv1studiosdkaclListResponse(rsp *http.Response) (*POSTv1studiosdkaclListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &POSTv1studiosdkaclListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Wire95a77e17aef6a0c48e1829638788a4dec1654a5c42fd6549e0c42f7eea24f35c
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePOSTv1studiosdkreportsGetResponse parses an HTTP response from a POSTv1studiosdkreportsGetWithResponse call
func ParsePOSTv1studiosdkreportsGetResponse(rsp *http.Response) (*POSTv1studiosdkreportsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &POSTv1studiosdkreportsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WireB42a7344fc0606034fc05c388a62f83c484228cb1e9be8bf4055ff09f8f4a044
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePOSTv1studiosdkreportsListResponse parses an HTTP response from a POSTv1studiosdkreportsListWithResponse call
func ParsePOSTv1studiosdkreportsListResponse(rsp *http.Response) (*POSTv1studiosdkreportsListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &POSTv1studiosdkreportsListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Wire38fcb57c86eb44d564d0165fe128aec29a7664c7bb39427502b08df9aa42649a
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
